[2024-05-12 11:44:13] 


[2024-05-12 11:44:13] Started the Error Log File
[2024-05-12 11:44:15] No errors occurred
[2024-05-12 11:44:15] Closed the Error Log File




[2024-05-12 11:44:23] 


[2024-05-12 11:44:23] Started the Error Log File
[2024-05-12 11:44:24] No errors occurred
[2024-05-12 11:44:24] Closed the Error Log File




[2024-05-12 11:45:07] 


[2024-05-12 11:45:07] Started the Error Log File
[2024-05-12 11:45:08] No errors occurred
[2024-05-12 11:45:08] Closed the Error Log File




[2024-05-12 11:46:17] 


[2024-05-12 11:46:17] Started the Error Log File
[2024-05-12 11:46:33] No errors occurred
[2024-05-12 11:46:33] Closed the Error Log File




[2024-05-12 11:48:20] 


[2024-05-12 11:48:20] Started the Error Log File
[2024-05-12 11:51:44] 


[2024-05-12 11:51:44] Started the Error Log File
[2024-05-12 11:52:52] 


[2024-05-12 11:52:52] Started the Error Log File
[2024-05-12 11:53:07] No errors occurred
[2024-05-12 11:53:07] Closed the Error Log File




[2024-05-12 12:59:37] 


[2024-05-12 12:59:37] Started the Error Log File
[2024-05-12 12:59:38] No errors occurred
[2024-05-12 12:59:38] Closed the Error Log File




[2024-05-12 13:05:21] 


[2024-05-12 13:05:21] Started the Error Log File
[2024-05-12 13:05:22] No errors occurred
[2024-05-12 13:05:22] Closed the Error Log File




[2024-05-12 13:06:28] 


[2024-05-12 13:06:28] Started the Error Log File
[2024-05-12 13:06:29] No errors occurred
[2024-05-12 13:06:29] Closed the Error Log File




[2024-05-12 13:07:18] 


[2024-05-12 13:07:18] Started the Error Log File
[2024-05-12 13:07:19] No errors occurred
[2024-05-12 13:07:19] Closed the Error Log File




[2024-05-12 13:08:04] 


[2024-05-12 13:08:04] Started the Error Log File
[2024-05-12 13:08:05] No errors occurred
[2024-05-12 13:08:05] Closed the Error Log File




[2024-05-12 13:09:16] 


[2024-05-12 13:09:16] Started the Error Log File
[2024-05-12 13:09:18] No errors occurred
[2024-05-12 13:09:18] Closed the Error Log File




[2024-05-12 13:11:27] 


[2024-05-12 13:11:27] Started the Error Log File
[2024-05-12 13:11:28] No errors occurred
[2024-05-12 13:11:28] Closed the Error Log File




[2024-05-12 13:12:45] 


[2024-05-12 13:12:45] Started the Error Log File
[2024-05-12 13:12:46] No errors occurred
[2024-05-12 13:12:46] Closed the Error Log File




[2024-05-12 13:17:48] 


[2024-05-12 13:17:48] Started the Error Log File
[2024-05-12 13:17:49] No errors occurred
[2024-05-12 13:17:49] Closed the Error Log File




[2024-05-12 13:31:52] 


[2024-05-12 13:31:52] Started the Error Log File
[2024-05-12 13:31:53] No errors occurred
[2024-05-12 13:31:53] Closed the Error Log File




[2024-05-12 13:32:40] 


[2024-05-12 13:32:40] Started the Error Log File
[2024-05-12 13:33:10] No errors occurred
[2024-05-12 13:33:10] Closed the Error Log File




[2024-05-12 13:39:14] 


[2024-05-12 13:39:14] Started the Error Log File
[2024-05-12 13:39:21] No errors occurred
[2024-05-12 13:39:21] Closed the Error Log File




[2024-05-12 13:39:53] 


[2024-05-12 13:39:53] Started the Error Log File
[2024-05-12 13:39:54] No errors occurred
[2024-05-12 13:39:54] Closed the Error Log File




[2024-05-12 13:52:19] 


[2024-05-12 13:52:19] Started the Error Log File
[2024-05-12 13:53:53] 


[2024-05-12 13:53:53] Started the Error Log File
[2024-05-12 13:54:14] 


[2024-05-12 13:54:14] Started the Error Log File
[2024-05-12 13:54:14] No errors occurred
[2024-05-12 13:54:14] Closed the Error Log File




[2024-05-12 13:54:31] 


[2024-05-12 13:54:31] Started the Error Log File
[2024-05-12 13:58:45] 


[2024-05-12 13:58:45] Started the Error Log File
[2024-05-12 13:58:46] No errors occurred
[2024-05-12 13:58:46] Closed the Error Log File




[2024-05-12 13:59:05] 


[2024-05-12 13:59:05] Started the Error Log File
[2024-05-12 13:59:06] No errors occurred
[2024-05-12 13:59:06] Closed the Error Log File




[2024-05-12 14:00:11] 


[2024-05-12 14:00:11] Started the Error Log File
[2024-05-12 14:00:25] No errors occurred
[2024-05-12 14:00:25] Closed the Error Log File




[2024-05-12 14:14:32] 


[2024-05-12 14:14:32] Started the Error Log File
[2024-05-12 14:14:35] No errors occurred
[2024-05-12 14:14:35] Closed the Error Log File




[2024-05-12 14:14:49] 


[2024-05-12 14:14:49] Started the Error Log File
[2024-05-12 14:15:27] No errors occurred
[2024-05-12 14:15:27] Closed the Error Log File




[2024-05-12 16:26:56] 


[2024-05-12 16:26:56] Started the Error Log File
[2024-05-12 16:27:48] No errors occurred
[2024-05-12 16:27:48] Closed the Error Log File




[2024-05-12 16:27:50] 


[2024-05-12 16:27:50] Started the Error Log File
[2024-05-12 16:27:57] No errors occurred
[2024-05-12 16:27:57] Closed the Error Log File




[2024-05-12 16:30:38] 


[2024-05-12 16:30:38] Started the Error Log File
[2024-05-12 16:30:48] No errors occurred
[2024-05-12 16:30:48] Closed the Error Log File




[2024-05-12 16:33:21] 


[2024-05-12 16:33:21] Started the Error Log File
[2024-05-12 16:33:39] No errors occurred
[2024-05-12 16:33:39] Closed the Error Log File




[2024-05-12 16:33:56] 


[2024-05-12 16:33:56] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\main_snake_game.py", line 425, in patchnotes
    self.scrollable_frame = ctk.CTkScrollableFrame(self.info_canvas, bg='Grey20', highlightbackground='Black', highlightthickness=5) # pylint: disable=line-too-long
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CTkScrollableFrame.__init__() got an unexpected keyword argument 'bg'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\main_snake_game.py", line 425, in patchnotes
    self.scrollable_frame = ctk.CTkScrollableFrame(self.info_canvas, bg='Grey20', highlightbackground='Black', highlightthickness=5) # pylint: disable=line-too-long
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CTkScrollableFrame.__init__() got an unexpected keyword argument 'bg'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\main_snake_game.py", line 425, in patchnotes
    self.scrollable_frame = ctk.CTkScrollableFrame(self.info_canvas, bg='Grey20', highlightbackground='Black', highlightthickness=5) # pylint: disable=line-too-long
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CTkScrollableFrame.__init__() got an unexpected keyword argument 'bg'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\main_snake_game.py", line 425, in patchnotes
    self.scrollable_frame = ctk.CTkScrollableFrame(self.info_canvas, bg='Grey20', highlightbackground='Black', highlightthickness=5) # pylint: disable=line-too-long
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CTkScrollableFrame.__init__() got an unexpected keyword argument 'bg'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\main_snake_game.py", line 425, in patchnotes
    self.scrollable_frame = ctk.CTkScrollableFrame(self.info_canvas, bg='Grey20', highlightbackground='Black', highlightthickness=5) # pylint: disable=line-too-long
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CTkScrollableFrame.__init__() got an unexpected keyword argument 'bg'
[2024-05-12 16:34:01] No errors occurred
[2024-05-12 16:34:01] Closed the Error Log File




[2024-05-12 16:35:17] 


[2024-05-12 16:35:17] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "c:\Users\wimjr\Documents\GitHub\Snake_Game_V3\main_snake_game.py", line 425, in patchnotes
    self.scrollable_frame = ctk.CTkScrollableFrame(self.info_canvas, width=600, height=400, bg='Grey20')
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CTkScrollableFrame.__init__() got an unexpected keyword argument 'bg'
[2024-05-12 16:35:20] No errors occurred
[2024-05-12 16:35:20] Closed the Error Log File




[2024-05-12 16:35:33] 


[2024-05-12 16:35:33] Started the Error Log File
[2024-05-12 16:35:59] No errors occurred
[2024-05-12 16:35:59] Closed the Error Log File




[2024-05-12 16:41:56] 


[2024-05-12 16:41:56] Started the Error Log File
[2024-05-12 16:42:14] No errors occurred
[2024-05-12 16:42:14] Closed the Error Log File




[2024-05-12 16:44:00] 


[2024-05-12 16:44:00] Started the Error Log File
[2024-05-12 16:44:17] No errors occurred
[2024-05-12 16:44:17] Closed the Error Log File




[2024-05-12 16:44:26] 


[2024-05-12 16:44:26] Started the Error Log File
[2024-05-12 16:44:32] No errors occurred
[2024-05-12 16:44:32] Closed the Error Log File




[2024-05-12 16:55:40] 


[2024-05-12 16:55:40] Started the Error Log File
[2024-05-12 16:55:51] No errors occurred
[2024-05-12 16:55:51] Closed the Error Log File




[2024-05-12 16:56:01] 


[2024-05-12 16:56:01] Started the Error Log File
[2024-05-12 16:56:40] No errors occurred
[2024-05-12 16:56:40] Closed the Error Log File




[2024-05-12 16:56:59] 


[2024-05-12 16:56:59] Started the Error Log File
[2024-05-12 16:57:05] No errors occurred
[2024-05-12 16:57:05] Closed the Error Log File




[2024-05-12 16:57:12] 


[2024-05-12 16:57:12] Started the Error Log File
[2024-05-12 16:57:20] No errors occurred
[2024-05-12 16:57:20] Closed the Error Log File




[2024-05-12 16:57:38] 


[2024-05-12 16:57:38] Started the Error Log File
[2024-05-12 16:57:47] No errors occurred
[2024-05-12 16:57:47] Closed the Error Log File




[2024-05-12 16:57:56] 


[2024-05-12 16:57:56] Started the Error Log File
[2024-05-12 16:58:02] No errors occurred
[2024-05-12 16:58:02] Closed the Error Log File




[2024-05-12 16:58:23] 


[2024-05-12 16:58:23] Started the Error Log File
[2024-05-12 16:58:29] No errors occurred
[2024-05-12 16:58:29] Closed the Error Log File




[2024-05-12 16:58:38] 


[2024-05-12 16:58:38] Started the Error Log File
[2024-05-12 16:58:45] No errors occurred
[2024-05-12 16:58:45] Closed the Error Log File




[2024-05-12 16:58:54] 


[2024-05-12 16:58:54] Started the Error Log File
[2024-05-12 17:04:36] No errors occurred
[2024-05-12 17:04:36] Closed the Error Log File




[2024-05-12 17:04:38] 


[2024-05-12 17:04:38] Started the Error Log File
[2024-05-12 17:04:39] No errors occurred
[2024-05-12 17:04:39] Closed the Error Log File




[2024-05-12 17:11:57] 


[2024-05-12 17:11:57] Started the Error Log File
[2024-05-12 17:12:13] No errors occurred
[2024-05-12 17:12:13] Closed the Error Log File




[2024-05-12 17:16:55] 


[2024-05-12 17:16:55] Started the Error Log File
[2024-05-12 17:17:18] No errors occurred
[2024-05-12 17:17:18] Closed the Error Log File




[2024-05-12 17:38:41] 


[2024-05-12 17:38:41] Started the Error Log File
[2024-05-12 17:39:58] No errors occurred
[2024-05-12 17:39:58] Closed the Error Log File




[2024-05-12 17:42:27] 


[2024-05-12 17:42:27] Started the Error Log File
[2024-05-12 17:42:43] No errors occurred
[2024-05-12 17:42:43] Closed the Error Log File




[2024-05-12 17:43:21] 


[2024-05-12 17:43:21] Started the Error Log File
[2024-05-12 17:43:34] No errors occurred
[2024-05-12 17:43:34] Closed the Error Log File




[2024-05-12 17:45:26] 


[2024-05-12 17:45:26] Started the Error Log File
[2024-05-12 17:45:33] No errors occurred
[2024-05-12 17:45:33] Closed the Error Log File




[2024-05-12 19:51:15] 


[2024-05-12 19:51:15] Started the Error Log File
[2024-05-12 19:51:29] No errors occurred
[2024-05-12 19:51:29] Closed the Error Log File




[2024-05-13 18:56:20] 


[2024-05-13 18:56:20] Started the Error Log File
[2024-05-13 18:57:48] No errors occurred
[2024-05-13 18:57:48] Closed the Error Log File




[2024-05-13 18:58:36] 


[2024-05-13 18:58:36] Started the Error Log File
[2024-05-13 18:58:44] No errors occurred
[2024-05-13 18:58:44] Closed the Error Log File




[2024-05-13 18:58:53] 


[2024-05-13 18:58:53] Started the Error Log File
[2024-05-13 18:59:00] No errors occurred
[2024-05-13 18:59:00] Closed the Error Log File




[2024-05-13 18:59:05] 


[2024-05-13 18:59:05] Started the Error Log File
[2024-05-13 18:59:11] No errors occurred
[2024-05-13 18:59:11] Closed the Error Log File




[2024-05-13 18:59:20] 


[2024-05-13 18:59:20] Started the Error Log File
[2024-05-13 18:59:39] No errors occurred
[2024-05-13 18:59:39] Closed the Error Log File




[2024-05-13 19:04:04] 


[2024-05-13 19:04:04] Started the Error Log File
[2024-05-13 19:04:51] No errors occurred
[2024-05-13 19:04:51] Closed the Error Log File




[2024-05-13 19:05:42] 


[2024-05-13 19:05:42] Started the Error Log File
[2024-05-13 19:06:02] No errors occurred
[2024-05-13 19:06:02] Closed the Error Log File




[2024-05-13 19:06:08] 


[2024-05-13 19:06:08] Started the Error Log File
[2024-05-13 19:06:27] No errors occurred
[2024-05-13 19:06:27] Closed the Error Log File




[2024-05-13 19:06:30] 


[2024-05-13 19:06:30] Started the Error Log File
[2024-05-13 19:06:58] No errors occurred
[2024-05-13 19:06:58] Closed the Error Log File




[2024-05-13 19:07:03] 


[2024-05-13 19:07:03] Started the Error Log File
[2024-05-13 19:08:31] No errors occurred
[2024-05-13 19:08:31] Closed the Error Log File




[2024-05-13 19:08:54] 


[2024-05-13 19:08:54] Started the Error Log File
[2024-05-13 19:13:00] No errors occurred
[2024-05-13 19:13:00] Closed the Error Log File




[2024-05-13 19:13:35] 


[2024-05-13 19:13:35] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
[2024-05-13 19:13:42] No errors occurred
[2024-05-13 19:13:42] Closed the Error Log File




[2024-05-13 19:15:19] 


[2024-05-13 19:15:19] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text=main['date'],
         ~~~~^^^^^^^^
KeyError: 'date'
[2024-05-13 19:15:22] No errors occurred
[2024-05-13 19:15:22] Closed the Error Log File




[2024-05-13 19:20:24] 


[2024-05-13 19:20:24] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text=main['date'],
         ~~~~^^^^^^^^
KeyError: 'date'
[2024-05-13 19:20:26] No errors occurred
[2024-05-13 19:20:26] Closed the Error Log File




[2024-05-13 19:20:38] 


[2024-05-13 19:20:38] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text=main['date'],
         ~~~~^^^^^^^^
KeyError: 'date'
[2024-05-13 19:20:41] No errors occurred
[2024-05-13 19:20:41] Closed the Error Log File




[2024-05-13 19:20:48] 


[2024-05-13 19:20:48] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
[2024-05-13 19:20:53] No errors occurred
[2024-05-13 19:20:53] Closed the Error Log File




[2024-05-13 19:21:24] 


[2024-05-13 19:21:24] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
[2024-05-13 19:21:29] No errors occurred
[2024-05-13 19:21:29] Closed the Error Log File




[2024-05-13 19:22:13] 


[2024-05-13 19:22:13] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
[2024-05-13 19:22:17] No errors occurred
[2024-05-13 19:22:17] Closed the Error Log File




[2024-05-13 19:22:20] 


[2024-05-13 19:22:20] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 73, in patchnotes_command
    self.functions['patchnotes']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 433, in patchnotes
    text="Version: " + note['version'], # pylint: disable=line-too-long
                       ~~~~^^^^^^^^^^^
KeyError: 'version'
[2024-05-13 19:22:25] No errors occurred
[2024-05-13 19:22:25] Closed the Error Log File




[2024-05-13 19:23:00] 


[2024-05-13 19:23:00] Started the Error Log File
[2024-05-13 19:23:11] No errors occurred
[2024-05-13 19:23:11] Closed the Error Log File




[2024-05-13 19:31:08] 


[2024-05-13 19:31:08] Started the Error Log File
[2024-05-13 19:31:27] No errors occurred
[2024-05-13 19:31:27] Closed the Error Log File




[2024-05-13 19:31:30] 


[2024-05-13 19:31:30] Started the Error Log File
[2024-05-13 19:31:41] No errors occurred
[2024-05-13 19:31:41] Closed the Error Log File




[2024-05-13 19:31:48] 


[2024-05-13 19:31:48] Started the Error Log File
[2024-05-13 19:31:58] No errors occurred
[2024-05-13 19:31:58] Closed the Error Log File




[2024-05-13 19:32:06] 


[2024-05-13 19:32:06] Started the Error Log File
[2024-05-13 19:32:12] No errors occurred
[2024-05-13 19:32:12] Closed the Error Log File




[2024-05-13 19:32:19] 


[2024-05-13 19:32:19] Started the Error Log File
[2024-05-13 19:32:26] No errors occurred
[2024-05-13 19:32:26] Closed the Error Log File




[2024-05-13 19:32:44] 


[2024-05-13 19:32:44] Started the Error Log File
[2024-05-13 19:32:47] No errors occurred
[2024-05-13 19:32:47] Closed the Error Log File




[2024-05-13 19:33:03] 


[2024-05-13 19:33:03] Started the Error Log File
[2024-05-13 19:33:11] No errors occurred
[2024-05-13 19:33:11] Closed the Error Log File




[2024-05-13 19:33:18] 


[2024-05-13 19:33:18] Started the Error Log File
[2024-05-13 19:33:31] No errors occurred
[2024-05-13 19:33:31] Closed the Error Log File




[2024-05-13 19:33:56] 


[2024-05-13 19:33:56] Started the Error Log File
[2024-05-13 19:34:01] No errors occurred
[2024-05-13 19:34:01] Closed the Error Log File




[2024-05-13 19:34:05] 


[2024-05-13 19:34:05] Started the Error Log File
[2024-05-13 19:35:48] No errors occurred
[2024-05-13 19:35:48] Closed the Error Log File




[2024-05-13 19:35:51] 


[2024-05-13 19:35:51] Started the Error Log File
[2024-05-13 19:36:13] No errors occurred
[2024-05-13 19:36:13] Closed the Error Log File




[2024-05-13 19:38:43] 


[2024-05-13 19:38:43] Started the Error Log File
[2024-05-13 19:38:56] No errors occurred
[2024-05-13 19:38:56] Closed the Error Log File




