[2024-06-30 13:49:42] 


[2024-06-30 13:49:42] Started the Error Log File
[2024-06-30 13:49:59] No errors occurred
[2024-06-30 13:49:59] Closed the Error Log File




[2024-06-30 13:50:21] 


[2024-06-30 13:50:21] Started the Error Log File
[2024-06-30 13:50:25] No errors occurred
[2024-06-30 13:50:25] Closed the Error Log File




[2024-06-30 13:50:46] 


[2024-06-30 13:50:46] Started the Error Log File
[2024-06-30 13:51:08] No errors occurred
[2024-06-30 13:51:08] Closed the Error Log File




[2024-06-30 13:51:34] 


[2024-06-30 13:51:34] Started the Error Log File
[2024-06-30 13:51:39] No errors occurred
[2024-06-30 13:51:39] Closed the Error Log File




[2024-06-30 13:55:31] 


[2024-06-30 13:55:31] Started the Error Log File
[2024-06-30 13:55:42] No errors occurred
[2024-06-30 13:55:42] Closed the Error Log File




[2024-06-30 13:56:32] 


[2024-06-30 13:56:32] Started the Error Log File
[2024-06-30 13:57:07] No errors occurred
[2024-06-30 13:57:07] Closed the Error Log File




[2024-06-30 14:01:01] 


[2024-06-30 14:01:01] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 391, in update_text_position
    canvas_width = self.main_canvas.winfo_width() // 2 + 80
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1354, in winfo_width
    self.tk.call('winfo', 'width', self._w))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bad window path name ".!snakeclassicgame"
[2024-06-30 14:01:54] No errors occurred
[2024-06-30 14:01:54] Closed the Error Log File




[2024-06-30 14:01:55] 


[2024-06-30 14:01:55] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 391, in update_text_position
    canvas_width = self.main_canvas.winfo_width() // 2 + 80
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1354, in winfo_width
    self.tk.call('winfo', 'width', self._w))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bad window path name ".!snakeclassicgame"
[2024-06-30 14:02:16] No errors occurred
[2024-06-30 14:02:16] Closed the Error Log File




[2024-06-30 14:02:17] 


[2024-06-30 14:02:17] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 391, in update_text_position
    canvas_width = self.main_canvas.winfo_width() // 2 + 80
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1354, in winfo_width
    self.tk.call('winfo', 'width', self._w))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: bad window path name ".!snakeclassicgame"
[2024-06-30 14:13:26] No errors occurred
[2024-06-30 14:13:26] Closed the Error Log File




[2024-06-30 14:13:28] 


[2024-06-30 14:13:28] Started the Error Log File
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\wimjr\AppData\Local\Programs\Python\Python311\Lib\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 485, in home_button_command
    self.button_commands.home_command()
  File "e:\Snake_game_V3\Snake_Game_V3\Logic\buttonpanel_snake_game.py", line 30, in home_command
    self.functions['return_home']()
  File "e:\Snake_game_V3\Snake_Game_V3\main_snake_game.py", line 1129, in return_home
    self.classic_snake_canvas.destroy_button_panel()
  File "e:\Snake_game_V3\Snake_Game_V3\Games\snake_classic_game_2.py", line 443, in destroy_button_panel
    self.create_button_panel.destroy()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ClickButtonPanel' object has no attribute 'destroy'
[2024-06-30 14:13:33] No errors occurred
[2024-06-30 14:13:33] Closed the Error Log File




=




[2024-06-30 14:17:07] 


[2024-06-30 14:17:07] Started the Error Log File
[2024-06-30 14:17:25] No errors occurred
[2024-06-30 14:17:25] Closed the Error Log File




[2024-06-30 14:17:27] 


[2024-06-30 14:17:27] Started the Error Log File
[2024-06-30 14:21:02] No errors occurred
[2024-06-30 14:21:02] Closed the Error Log File




[2024-06-30 14:21:03] 


[2024-06-30 14:21:03] Started the Error Log File
[2024-06-30 14:21:35] No errors occurred
[2024-06-30 14:21:35] Closed the Error Log File




[2024-06-30 14:22:06] 


[2024-06-30 14:22:06] Started the Error Log File
[2024-06-30 14:22:27] No errors occurred
[2024-06-30 14:22:27] Closed the Error Log File




